[package]
name = "roid_rage"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
nalgebra = "0.19.0"
ncollide2d = "0.21.0"

[dependencies.amethyst]
version = "0.13"
features = ["metal"]

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
