[package]
name = "rr-pilot"
version = "0.1.0"
authors = ["Austin Bingham <austin.bingham@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.19"
num = "0.2.1"
serde_derive="1.0"
roid_rage = { path = "../roid-rage" }

[dependencies.serde]
version = "1.0"
features = ["derive"]