POST http://localhost:8000/update HTTP/1.1
content-type: application/json

{
    "width": 800,
    "height": 600,
    "firing_position": [400, 300],
    "bullet_speed": 1000,
    "roids": [
        {
            "id": 1,
            "radius": 50.3,
            "position": [20, 250],
            "velocity": [20.3, 40.6]
        },
        {
            "id": 2,
            "radius": 19.564,
            "position": [204, 25],
            "velocity": [200.3, 140.6]
        }
    ]
}

###

# GET http://localhost:8000/message/1 HTTP/1.1