[package]
edition = "2021"
name = "steering"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roid-rage-grpc = {path = "../roid-rage-grpc"}
sted = {path = "../sted"}
float-cmp = "0.6.0"